name: DevOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev

      - name: Mostrar estrutura do projeto
        run: |
          echo "Estrutura do projeto:"
          ls -lah

      - name: Build pacote .deb
        run: |
          dpkg-deb --build gerador-senha-devops-pkg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gerador-senha-devops
          path: gerador-senha-devops-pkg.deb
